# Generated by Django 3.2.2 on 2022-01-17 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='owner',
        ),
    ]
