# Generated by Django 3.2.2 on 2021-07-01 04:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following_set',
            field=models.ManyToManyField(blank=True, related_name='followed_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
