# Generated by Django 3.2.2 on 2021-07-06 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_user_following_set'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
